Update experiment config : Bug in multi_proc
When setting `exec_mode = ExecutionMode()`, the error:
TypeError: list indices must be integers or slices, not str

This is due to there only being 1 dictionary in the list inside M. If
another dictionary is added, the error goes away.
Removing the multi_proc requirement also makes the error go away